### ISSUE TITLE
[Windows] Change events do not fire when file is at drive root

### ISSUE THREAD

**Issue by lwblackledge** [atom/node-pathwatcher#102]
If the file is at the drive root the change event in `HandleWatcher.onEvent` fires but it does not fire the change in the `PathWatcher.onChange` method because the path provided to `HandleWatcher.onEvent` contains `\\`, while the `@path` variable does not.

This has been observed on Windows 10 but does not occur on linux.

**Comment by zcbenz** [comment]
Closed with #103.
