### ISSUE TITLE
Error: A dynamic link library DLL initialization routine failed. 

### ISSUE THREAD

**Issue by Montaldo** [atom/node-pathwatcher#108]
I am trying to get pathwatcher working with one of the electron example apps on the [electron-sample-apps](https://github.com/hokein/electron-sample-apps) repo.

**package.json**
`{
  "name": "pathwather-test",
  "version": "0.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron-prebuilt-compile": "^1.2.2"
  },
  "dependencies": {
    "pathwatcher": "^6.7.0"
  }
}`

When adding the line `require('pathwatcher')` to any of my sources file it get the following [error](http://imgur.com/nKyoP7b).

- Windows 10 x64
- npm version 3.9.5
- node version 4.4.5

**Comment by Montaldo** [comment]
Appearantly this was an issue with electron. Needed to run electron-rebuild to get is all fixed!

**Comment by UziTech** [comment]
@Montaldo could you list the steps you used to fix this issue. I am having the same issue and have not gotten `electron-rebuild` to work

**Comment by UziTech** [comment]
What fixed it for me was to run `apm i` then `apm rebuild`
