### ISSUE TITLE
Can't close the watcher

### ISSUE THREAD

**Issue by jpruiz114** [atom/node-pathwatcher#113]
Got this:

TypeError: pathWatcher.close is not a function

... while trying to close the watcher. What's the way to close it?

Thanks!

**Comment by thomasjo** [comment]
[`PathWatcher.closeAllWatchers`](https://github.com/atom/node-pathwatcher/blob/4b249d31eef36a6024652a0787b4044ecbd7aa49/src/main.coffee#L116)
