### ISSUE TITLE
dlopen error on OS X Mavericks and node 0.10

### ISSUE THREAD

**Issue by deiga** [atom/node-pathwatcher#28]
I'm trying to include `PathWatcher` in my project, but I get this error on start.

```
"Uncaught Error: dlopen(/Users/timosand/Development/reposive-syncer/node_modules/pathwatcher/build/Release/pathwatcher.node, 1): no suitable image found.  Did find:
	/Users/timosand/Development/reposive-syncer/node_modules/pathwatcher/build/Release/pathwatcher.node: mach-o, but wrong architecture", source: /Users/timosand/Development/reposive-syncer/node_modules/pathwatcher/node_modules/bindings/bindings.js (83)
```

**Comment by kevinsawicki** [comment]
The `mach-o, but wrong architecture` seems to suggest that somehow pathwatcher was incorrectly built and could not be properly required because of it.

I'm going to close this out for now, please comment if you are still experiencing this issue and what version of node/npm you are now using.
