### ISSUE TITLE
[Linux] Feedback

### ISSUE THREAD

**Issue by as3boyan** [atom/node-pathwatcher#33]
Works incredibly fast.

When file gets deleted and recreated again very quickly(for example when compiler generates JavaScript file), watcher emits `change` and `delete` and stops watching file, so I had to manually wait 1500 ms, before checking if file exists, and if it exists - then start watching again `Pathwatcher.watch`, and check if file modified since last time to detect if file tab needs reloading.(in my IDE based on atom-shell).

Without delay of 1500 ms, it doesn't seems to start watching again.

Great job guys! Very fast!

**Comment by kevinsawicki** [comment]
Closing this out since more details weren't provided, please comment if you are still experiencing this issue.
