### ISSUE TITLE
Unable to use this module in Electron's renderer process

### ISSUE THREAD

**Issue by ducky427** [atom/node-pathwatcher#69]
Hi,
I am using `electron` v0.25.1 and `pathwatcher` v4.4.0. When I require `pathwatcher` in my app's renderer process, I get the following error:

```
var Pathwatcher = require('pathwatcher');
Uncaught Error: Module did not self-register.message: "Module did not self-register."stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: 
```

Any help would be much appreciated.

Thanks

**Comment by kevinsawicki** [comment]
How did you install/build `pathwatcher`? Did you use `apm` or `npm`?

**Comment by ducky427** [comment]
thanks @kevinsawicki.

I used npm. I did a `npm install pathwatcher`. I even tried instructions as given in electron docs [here](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-npm-way) without any success. 

I have node v0.10.37 installed and I use npm v2.8.3. I am on linux x64 bit arch.

Could it be a node version mismatch with electron's io.js version?

**Comment by kevinsawicki** [comment]
> Could it be a node version mismatch with electron's io.js version?

Yup, you need to compile native modules against the v8 headers that ship with electron.

You can use https://github.com/atom/apm for this.

```sh
$ npm install --save-dev atom-package-manager
$ apm install # installs all dependencies in your package.json
```

**Comment by ducky427** [comment]
Thanks @kevinsawicki. 

After doing this, when I try it now, electron crashes with the following error:

```
/.../electron/electron --type=renderer --force-device-scale-factor=1 --no-sandbox --enable-deferred-image-decoding --lang=en-GB --node-integration=true --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --disable-accelerated-video-decode --channel=500923.1.1082692326: symbol lookup error: /.../node_modules/pathwatcher/build/Release/pathwatcher.node: undefined symbol: _ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEEiPS5_
```

Still looks like the native module isn't compiled correctly.

I really appreciate your help on this.

**Comment by kevinsawicki** [comment]
Hmm, what version of electron are you using? I'm not sure pathwatcher is compatible with the current electron release that uses Chrome 42

**Comment by ducky427** [comment]
I am using the latest version of electron [v0.25.1](https://github.com/atom/electron/releases/tag/v0.25.1) which was released two days back.

**Comment by ducky427** [comment]
Thats it! This module compatible with electron v0.24.0.

**Comment by zcbenz** [comment]
@ducky427 You can follow [this doc](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-npm-way) to build modules against 0.25.1, `apm` is mostly used for the version used by atom and sometimes is not up-to-date.
