### ISSUE TITLE
6.3.0 fails to build on windows

### ISSUE THREAD

**Issue by maxkorp** [atom/node-pathwatcher#96]
6.2.5 is building successfully. 
```bash
..\src\common.cc(150): error C2664: 'void Nan::ReturnValue<T>::Set(uint32_t)': cannot convert argument 1 from 'v8::Handle<v8::Value>' to 'bool' [C:\Projects\temp\node_modules\pathwatcher\build\pathwatcher.vcxproj]

with
[
    T=v8::Value
]
..\src\common.cc(150): note: no user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

Fortunately i've got my packages shrinkwrapped, but unfortunately shrinkwrap is working for every package EXCEPT pathwatcher (shrinkwrapped to 6.2.5 but it installs 6.3.0, no clue why), so this is kind of blocking things up for a number of our developers :/.

**Comment by zcbenz** [comment]
Can you try whether `npm install pathwatcher` works for your?

**Comment by maxkorp** [comment]
It does. Interestingly, it works against 0.34, but not against 0.33, but that upgrade is causing other issues for me.

**Comment by itsnotvalid** [comment]
Would this be related to node.js version used with windows build of atom? It still ships with node v0.10.40 (for atom v1.2.4). It builds without problem with latest node (v4.2.1 stable).
